AtmoTrack_web_page/AtmoTrack_web_page/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace AtmoTrack_web_page.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Dashboard1()
        {
            // Verifica se o usuário está logado
            if (HttpContext.Session.GetString("LoggedUser") != null)
            {
                return View();
            }
            else
            {
                // Se não estiver logado, redireciona para a página de login
                return RedirectToAction("Index", "Login");
            }
            
        }

        private static readonly Random Random = new Random();

        // Endpoint que fornece dados em JSON
        [HttpGet]
        public IActionResult GetData()
        {
            // Gera dados aleatórios
            var labels = new[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul" };
            var values = new int[labels.Length];

            for (int i = 0; i < values.Length; i++)
            {
                // Gera valores aleatórios entre 1 e 100
                values[i] = Random.Next(1, 100);
            }

            var data = new
            {
                Labels = labels,
                Values = values
            };

            return Json(data);
        }
        public IActionResult Dashboard2()
        {
            // Verifica se o usuário está logado
            if (HttpContext.Session.GetString("LoggedUser") != null)
            {
                return View();
            }
            else
            {
                // Se não estiver logado, redireciona para a página de login
                return RedirectToAction("Index", "Login");
            }
        }
    }
}

AtmoTrack_web_page/AtmoTrack_web_page/Controllers/EmpresaController.cs
using AtmoTrack_web_page.DAO;
using AtmoTrack_web_page.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace AtmoTrack_web_page.Controllers
{
    public class EmpresaController : Controller
    {
        public IActionResult Index()
        {
            try
            {
                EmpresaDAO dao = new EmpresaDAO();
                var em = dao.Listagem();

                return View(em);
            }
            catch (Exception erro)
            {

            }
            return View();
        }

        public IActionResult NovoRegistro()
        {
            try
            {
                ViewBag.cadastroEmpresa = "I";
                EmpresaDAO dao = new EmpresaDAO();
                EmpresaViewModel em = new EmpresaViewModel();
                em.Id = dao.LastId();

                var estados = dao.GetAllStates().Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.Estado
                }).ToList();

                ViewBag.Estados = estados;

                return View("Form", em);
            }
            catch (Exception erro)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = erro.Message,
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
                };

                return View("Error", errorViewModel);
            }
        }

        public IActionResult Salvar(EmpresaViewModel em, string cadastroEmpresa)
        {
            try
            {
                var dao = new EmpresaDAO();
                if (cadastroEmpresa == "I")
                {
                    dao.Inserir(em);
                }
                else
                {
                    dao.Alterar(em);
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                return View("Error", erro.ToString());
            }
        }

        public IActionResult GetCidades(int estadoId)
        {
            try
            {
                EmpresaDAO dao = new EmpresaDAO();
                var cidades = dao.GetAllCitiesEstadoId(estadoId);
                return Json(cidades);
            }
            catch (Exception erro)
            {
                return Json(new { error = erro.Message });
            }
        }

        public IActionResult Editar(int id)
        {
            try
            {
                ViewBag.cadastroEmpresa = "A";
                EmpresaDAO dao = new EmpresaDAO();
                EmpresaViewModel em = dao.Consulta(id);
                var estados = dao.GetAllStates().Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.Estado
                }).ToList();

                ViewBag.Estados = estados;

                return View("Form", em);
            }
            catch (Exception erro)
            {
                return View("Erro", erro.ToString());
            }
        }

        public IActionResult Delete(int id)
        {
            try
            {
                EmpresaDAO dao = new EmpresaDAO();
                dao.Excluir(id);
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                return View("Erro", erro.ToString());
            }
        }

        public IActionResult Exibir(int id)
        {
            try
            {
                EmpresaDAO dao = new EmpresaDAO();
                var em = dao.Consulta(id);
                if (em == null)
                {
                    return NotFound();
                }

                var estado = dao.ConsultaEstado(em.EstadoId);

                ViewBag.EstadoNome = estado != null ? estado.Estado : "Estado não encontrado";

                if (estado == null)
                {
                    return NotFound();
                }

                var cidade = dao.ConsultaCidade(em.CidadeId);
                ViewBag.CidadeNome = cidade != null ? cidade.Cidade : "Estado não encontrado";

                return View("ExibirEmpresa", em);
            }
            catch (Exception erro)
            {
                return View("Erro", erro.ToString());
            }
        }
    }
}

AtmoTrack_web_page/AtmoTrack_web_page/Controllers/EquipamentoController.cs
using AtmoTrack_web_page.DAO;
using AtmoTrack_web_page.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Diagnostics;

namespace AtmoTrack_web_page.Controllers
{
    public class EquipamentoController : Controller
    {
        public IActionResult Index()
        {
            try
            {
                EquipamentoDAO dao = new EquipamentoDAO();
                var eq = dao.Listagem();


                return View(eq);
            }
            catch (Exception erro)
            {

            }
            return View();
        }

        public IActionResult NovoRegistro()
        {
            try
            {
                ViewBag.cadastroEquipamento = "I";
                EquipamentoDAO dao = new EquipamentoDAO();
                EquipamentoViewModel eq = new EquipamentoViewModel();
                eq.Id = dao.LastId();

                var empresas = dao.GetAllEmpresas().Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.NomeFantasia
                }).ToList();

                ViewBag.Empresas = empresas;

                return View("Form", eq);
            }
            catch (Exception erro)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = erro.Message,
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
                };

                return View("Error", errorViewModel);
            }
        }

        public IActionResult Salvar(EquipamentoViewModel em, string cadastroEquipamento)
        {
            try
            {
                var dao = new EquipamentoDAO();
                if (cadastroEquipamento == "I")
                {
                    dao.Inserir(em);
                }
                else
                {
                    dao.Alterar(em);
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                return View("Error", erro.ToString());
            }
        }

        public IActionResult Editar(int id)
        {
            try
            {
                ViewBag.cadastroEquipamento = "A";
                EquipamentoDAO dao = new EquipamentoDAO();
                EquipamentoViewModel eq = dao.Consulta(id);
                var empresas = dao.GetAllEmpresas().Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.NomeFantasia
                }).ToList();

                ViewBag.Empresas = empresas;

                return View("Form", eq);
            }
            catch (Exception erro)
            {
                return View("Erro", erro.ToString());
            }
        }

        public IActionResult Delete(int id)
        {
            try
            {
                EquipamentoDAO dao = new EquipamentoDAO();
                dao.Excluir(id);
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                return View("Erro", erro.ToString());
            }
        }

        public IActionResult Exibir(int id)
        {
            try
            {
                EquipamentoDAO dao = new EquipamentoDAO();
                var eq = dao.Consulta(id);
                if (eq == null)
                {
                    return NotFound();
                }

                var empresa = dao.ConsultaEmpresa(eq.EmpresaId);

                ViewBag.EmpresaNome = empresa != null ? empresa.NomeFantasia : "Empresa não encontrado";

                return View("ExibirEmpresa", eq);
            }
            catch (Exception erro)
            {
                return View("Erro", erro.ToString());
            }
        }
    }
}

AtmoTrack_web_page/AtmoTrack_web_page/Controllers/UsuarioController.cs
using AtmoTrack_web_page.DAO;
using AtmoTrack_web_page.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data.SqlClient;
using System.Diagnostics;

namespace AtmoTrack_web_page.Controllers
{
    public class UsuarioController : Controller
    {
        public IActionResult Index()
        {
            try
            {
                UsuarioDAO dao = new UsuarioDAO();
                var us = dao.Listagem();

                return View(us);
            }
            catch (Exception erro)
            {

            }
            return View();
        }

        public IActionResult NovoRegistro()
        {
            try
            {
                ViewBag.cadastroUsuario = "I";
                UsuarioDAO dao = new UsuarioDAO();
                UsuarioViewModel us = new UsuarioViewModel();
                us.Id = dao.LastId();

                var estados = dao.GetAllStates().Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.Estado
                }).ToList();

                ViewBag.Estados = estados;

                return View("Form",us);
            }
            catch (Exception erro)
            {
                var errorViewModel = new ErrorViewModel
                {
                    ErrorMessage = erro.Message,  
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
                };

                return View("Error", errorViewModel);
            }
        }

        public IActionResult GetCidades(int estadoId)
        {
            try
            {
                UsuarioDAO dao = new UsuarioDAO();
                var cidades = dao.GetAllCitiesEstadoId(estadoId);
                return Json(cidades);
            }
            catch (Exception erro)
            {
                return Json(new { error = erro.Message });
            }
        }

        public IActionResult Salvar(UsuarioViewModel us, string cadastroUsuario)
        {
            try
            {
                var dao = new UsuarioDAO();
                if(cadastroUsuario == "I")
                {
                    dao.Inserir(us);
                }
                else
                {
                    dao.Alterar(us);
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                return View("Error", erro.ToString());
            }
        }

        public IActionResult Editar(int id)
        {
            try
            {
                ViewBag.cadastroUsuario = "A";
                UsuarioDAO dao = new UsuarioDAO();
                UsuarioViewModel us = dao.Consulta(id);
                var estados = dao.GetAllStates().Select(e => new SelectListItem
                {
                    Value = e.Id.ToString(),
                    Text = e.Estado
                }).ToList();

                ViewBag.Estados = estados;

                return View("Form", us);
            }
            catch(Exception erro)
            {
                return View("Error", erro.ToString());
            }
        }

        public IActionResult Delete(int id)
        {
            try
            {
                UsuarioDAO dao = new UsuarioDAO();
                dao.Excluir(id);
                return RedirectToAction("Index");
            }catch (Exception erro)
            {
                return View("Error", erro.ToString());
            }
        }

        public IActionResult Exibir(int id)
        {
            try
            {
                UsuarioDAO dao = new UsuarioDAO();
                var us = dao.Consulta(id);
                if (us == null)
                {
                    return NotFound();
                }

                var estado = dao.ConsultaEstado(us.EstadoId);

                ViewBag.EstadoNome = estado != null ? estado.Estado : "Estado não encontrado";

                if(estado == null)
                {
                    return NotFound();
                }

                var cidade = dao.ConsultaCidade(estado.Id);
                ViewBag.CidadeNome = cidade != null ? cidade.Cidade : "Estado não encontrado";

                return View("VisualizarUsuario", us);
            }catch(Exception erro)
            {
                return View("Error", erro.ToString());
            }
        }
    }
}

AtmoTrack_web_page/AtmoTrack_web_page/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AtmoTrack_web_page</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AtmoTrack_web_page.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color:#14548C;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/logo_atmotrack_192x192.png" alt="Logo AtmoTrack" class="imgloogo" />
                </a>
                <div style="margin-left: 100px;" class="sloganHome">
                    <h1>AtmoTrack</h1>
                    <p>O futuro da medição</p>
                </div>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ms-auto">
                        <!-- Aqui adicionamos o 'ms-auto' -->
                        <li class="nav-item me-3">
                            <a class="nav-link" style="color: #4BE2F2;" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item me-3">
                            <a class="nav-link" style="color: #4BE2F2;" asp-area="" asp-controller="Home" asp-action="Sobre">Sobre</a>
                        </li>
                        <li class="nav-item me-4">
                            <div class="btn-group" role="group">
                                <button type="button" class="btn dropdown-toggle" style="color: #4BE2F2;" data-bs-toggle="dropdown" aria-expanded="false">
                                    DashBoards
                                </button>
                                <ul class="dropdown-menu" style="color:#4BE2F2; background-color: #112E3C">
                                    <li><a class="dropdown-item" style="color: #4BE2F2;" asp-controller="Dashboard" asp-action="Dashboard1">DashBoard 1</a></li>
                                    <li><a class="dropdown-item" style="color: #4BE2F2;" asp-controller="Dashboard" asp-action="Dashboard2">DashBoard 2</a></li>
                                </ul>
                            </div>

                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item me-4">
                                <div class="btn-group" role="group">
                                    <button type="button" class="btn dropdown-toggle" style="color: #4BE2F2;" data-bs-toggle="dropdown" aria-expanded="false">
                                        Registro Usuarios
                                    </button>
                                    <ul class="dropdown-menu" style="color:#4BE2F2; background-color: #112E3C">
                                        <li><a class="dropdown-item" style="color: #4BE2F2;" asp-controller="Usuario" asp-action="Index">Usuarios</a></li>
                                        <li><a class="dropdown-item" style="color: #4BE2F2;" asp-controller="Usuario" asp-action="NovoRegistro">Cadastro de Usuarios</a></li>
                                    </ul>
                                </div>

                            </li>
                            <li class="nav-item me-4">
                                <div class="btn-group" role="group">
                                    <button type="button" class="btn dropdown-toggle" style="color: #4BE2F2;" data-bs-toggle="dropdown" aria-expanded="false">
                                        Registro Empresas
                                    </button>
                                    <ul class="dropdown-menu" style="color:#4BE2F2; background-color: #112E3C">
                                        <li><a class="dropdown-item" style="color: #4BE2F2;" asp-controller="Empresa" asp-action="Index">Empresas</a></li>
                                        <li><a class="dropdown-item" style="color: #4BE2F2;" asp-controller="Empresa" asp-action="NovoRegistro">Cadastro de Empresas</a></li>
                                    </ul>
                                </div>

                            </li>
                            <li class="nav-item me-4">
                                <div class="btn-group" role="group">
                                    <button type="button" class="btn dropdown-toggle" style="color: #4BE2F2;" data-bs-toggle="dropdown" aria-expanded="false">
                                        Registro Equipamentos
                                    </button>
                                    <ul class="dropdown-menu" style="color:#4BE2F2; background-color: #112E3C">
                                        <li><a class="dropdown-item" style="color: #4BE2F2;" asp-controller="Equipamento" asp-action="Index">Equipamentos</a></li>
                                        <li><a class="dropdown-item" style="color: #4BE2F2;" asp-controller="Equipamento" asp-action="NovoRegistro">Cadastro de Equipamento</a></li>
                                    </ul>
                                </div>

                            </li>
                        }
                        
                        <div class="btn-group" role="group" aria-label="Basic example">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Logout", "Login")'">Logout</button>
                            }
                            else
                            {
                                <button type="button" class="btn btn-primary" onclick="window.location.href='@Url.Action("Index", "Login")'">Sign In</button>
                            }
                        </div>

                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container d-flex justify-content-center" style="min-height: 100vh;">
        <main role="main" class="pb-3 container-geral">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AtmoTrack_web_page - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>